### ISSUE TITLE
how to process a group of files?

### ISSUE THREAD

**Issue by dcsan** [julien/gulp-processhtml#5]
i'm trying to use this plugin to process a directory:

```js
gulp.task('html', function () {
  gulp.src('src/*.html')
    .pipe(processhtml())
    .pipe(gulp.dest('dist'));
});
```

but it seems i need to give a specific output file.

`[gulp] 'html' errored after 3.99 ms Missing fileName option for gulp-processhtml`

most other plugins seem to allow just piping into the output dest

```js
// Images
gulp.task('images', function() {
  return gulp.src('src/images/**/*')
    .pipe(cache(imagemin({ optimizationLevel: 3, progressive: true, interlaced: true })))
    .pipe(gulp.dest('dist/images'))
    .pipe(notify({ message: 'Images task complete' }));
});
 
```

i saw this answer but it seems a lot of work for just dealing with a group of files, is this not natively supported by the plugin?

http://stackoverflow.com/a/23099944/1163694

**Comment by jolyonruss** [comment]
Hi @julien I'd really like this as an option

**Comment by julien** [comment]
Hi @jolyonruss this is possible, since version 1.0.2 just forgot to close this issue
